DROP DATABASE IF EXISTS ImpactDb
CREATE DATABASE ImpactDb;

USE ImpactDb;

CREATE TABLE scholarship (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  student_name VARCHAR(30) UNIQUE NOT NULL,
  student_school VARCHAR(30) UNIQUE NOT NULL,
  student_gpa DECIMAL UNSIGNED NOT NUL
);

CREATE TABLE charity (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  charity_name VARCHAR(30) UNIQUE NOT NULL,
  charity_amount DECIMAL UNSIGNED NOT NULL,
  employee_id INT UNSIGNED NOT NULL,
  
);

CREATE TABLE peerFunding (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30) NOT NULL,
  amount_donated DECIMAL UNSIGNED NOT NULL
  employee_id INT UNSIGNED NOT NULL
);
